### ISSUE TITLE
Is there a reason for the daily release tag for runtimecore?

### ISSUE THREAD

**Issue by DanFTRX** [Esri/lerc#100]
Trying to find a given Lerc github release is very difficult with daily releases published of the same runetimecore version.   Is there a reason it is rebuilt daily?  Can it be removed from the release tags except for actual version changes?

**Comment by chri7325** [comment]
@DanFTRX I work on the runtimecore product and we use tags to synchronize our daily builds. Because lerc does not have an actual packaged release, github will display all tags under the release column. Once an actual release is created, all tags get hidden away and only releases will show up under the release column. @tmaurer3 would it be possible to create an actual vetted release to fix?

**Comment by chri7325** [comment]
Actually, I might've spoken too soon. When a release is created, it does hide all of the non release tags but once enough non release tags are created, they will eventually hide the actual releases. It looks like this is an issue that has been raised by github already but has yet to have a resolution on how to make this system a bit better https://github.community/t5/How-to-use-Git-and-GitHub/Tag-without-release/td-p/6255/page/2

**Comment by DanFTRX** [comment]
@chri7325 Perhaps links to all the actual releases could be added to the readme?

**Comment by DanFTRX** [comment]
As far as I can tell its just:
https://github.com/Esri/lerc/releases/tag/v1.0
https://github.com/Esri/lerc/releases/tag/v1.0.1
https://github.com/Esri/lerc/releases/tag/v2.0

**Comment by chri7325** [comment]
@DanFTRX those do appear to be documented in https://github.com/Esri/lerc/blob/master/CHANGELOG.md. I only consume this product but maybe a link to the changlog in the readme would be clean.

**Comment by tmaurer3** [comment]
I agree with DanFTRX, this ever growing number of daily runtimecore release tags is confusing. Soon we will have more releases than commits. How about deleting older releases on a regular basis? Do you really need to keep them all, for each and every day? You could keep daily releases for the past 4 weeks, then one per month for 12 months, and delete all else. Something along those lines? See 

https://help.github.com/en/articles/editing-and-deleting-releases

**Comment by chri7325** [comment]
@tmaurer3 we do have plans to delete all tags that were not useful after a release is complete. We build our 3rdparty libraries daily but only use a few selected heavily tested ones (somewhat of a release). I'll up the priority of that issue so we can clean these out.

**Comment by tmaurer3** [comment]
@chri7325  Sounds great!

**Comment by DanFTRX** [comment]
2 weeks until we have more releases than commits.  I still don't understand why github tags are neccessary to synchronize a build.

**Comment by chri7325** [comment]
@DanFTRX we build our product with many different 3rdparty libraries from source daily. We need to build from source due to static linking. This means that any changes we make to compilers and compiler flags need to rebuild all of our 3rdparty libraries with said settings. To synchronize builds, we tag every repo we have daily at noon and then start the build process using tags so any changes that are made after tagging are not picked up so our build pipeline, which takes many hours, can all build using the same snapshot.

We can potentially fork this project into our own org since this project is more public facing than others so we can add this metadata without hurting outside developers understanding of it. That should allow us to continue versioning everything without causing massive confusion.

**Comment by DanFTRX** [comment]
@chri7325 Ah, that makes some sense then.  Forking would be nice to keep the more public facing Lerc repo clean.   But I guess thats up to  you guys.

**Comment by chri7325** [comment]
We've implemented an automated tag cleanup job now. We'll only keep the most relevant tags during a release. When we release, we'll cleanup all tags in that release except for the final version of it. This should keep these tags cleaned up. I still hope github is able to make their releases interface a little nicer and only show the actual releases marked there but we'll have to wait and see.

**Comment by tmaurer3** [comment]
@chri7325  Thanks for the automated tag cleanup! This helps. The final solution is for GitHub to not treat every tag as a release. So let's just link this issue to their existing one: 
https://github.community/t5/How-to-use-Git-and-GitHub/Tag-without-release/td-p/6255/page/2

**Comment by tmaurer3** [comment]
@DanFTRX  The list of releases has been cleaned up to contain only a small number. Closing this issue.
